name: GunsPlus
main: team.GunsPlus.GunsPlus
version: 1.2.4
depend: [Spout]
soft-depend: [LWC, FurnaceAPI, WorldGuard, Showcase]
authors: [Atlan1, SirTyler]
description: >
             Guns+ ~ Guns, Guns, Guns Galore!
commands:
    guns+:
        description: Guns+ commands.
        aliases: [g+,guns,+]
        usage: /guns+ help - Displays the Help Menu.
permissions:
    gunsplus.*:
        description: Give all permissions
        children:
            gunsplus.hud: true
            gunsplus.command.reload: true
            gunsplus.command.list: true
            gunsplus.fire.all: true
            gunsplus.zoom.all: true
            gunsplus.reload.all: true
    gunsplus.hud:
        description: Give permission for showing the hud.
        default: true
    gunsplus.command.reload:
        description: Give permission for the reload command.
        default: op
    gunsplus.command.list:
        description: Give permission for the list command.
        default: true
    gunsplus.fire.all:
        description: Give permission to fire all guns.
        default: false
    gunsplus.zoom.all:
        description: Give permission to zoom all guns.
        default: false
    gunsplus.reload.all:
        description: Give permission to reload all guns.
        default: false
    gunsplus.craft.all:
        description: Gives permission to crafting all guns.
        default: false
